---
- name: playbook for local & global
  hosts: all
  vars: 
      URL: "kamleshhh.com"
  tasks:
    - name: global variable
      debug:
        msg: "{{URL}}"
    - name: local variable
      debug:
        msg: "{{name}}"
      vars:
        name: "shiva" 
...                 